AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AnalyseTrend Backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AnalyseTrendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: analyse_trend/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Events:
        AnalyseTrendChatId:
          Type: Api
          Properties:
            Path: /analyse_trend/chat/{id}
            Method: get
        AnalyseTrendChats:
          Type: Api
          Properties:
            Path: /analyse_trend/chats/
            Method: get
        AnalyseTrendChat:
          Type: Api
          Properties:
            Path: /analyse_trend/chat/
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AnalyseTrendApi:
    Description: "API Gateway endpoint URL for Prod stage for AnalyseTrend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyse_trend/"
  AnalyseTrendFunction:
    Description: "AnalyseTrend Lambda Function ARN"
    Value: !GetAtt AnalyseTrendFunction.Arn
  AnalyseTrendFunctionIamRole:
    Description: "Implicit IAM Role created for AnalyseTrend function"
    Value: !GetAtt AnalyseTrendFunctionRole.Arn
